# @author : Julien Pechberty
#
# https://help.github.com/en/actions
name: JAVA TD 5 - Tests runners
on:
  push:
    branches:
      - test-xi
jobs:
  run-test:
    name : Run Tests suite
    runs-on: ubuntu-latest
    strategy:
      #fail-fast: true
      matrix:
        java-version: [22]

    steps:
      - name: Starting RUNNER
        run: echo "Launching tests for JAVA ${{ matrix.java-version }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
      - name: Création de l'artefact des résultats des tests
        uses: actions/upload-artifact@v4
        with:
          name: ciMavenReport-${{ github.run_id }}
          path: target/surefire-reports
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Results            # Name of the check run which will be created
          artifact: ciMavenReport-${{ github.run_id }}    # Artifact name to download
          path: ${{ github.workspace }}/target/surefire-reports    # Path to test results
          reporter: java-junit        # Format of test results
          #java-version: ${{ matrix.java-version }}    # Java version

