# @author : Julien Pechberty
#
# https://help.github.com/en/actions
name: JAVA TD 5 - Tests runners
on:
  push:
    branches:
      - dev-qa
jobs:
  run-test:
    name : Run Tests suite
    runs-on: ubuntu-latest
    strategy:
      #fail-fast: true
      matrix:
        java-version: [22]

    steps:
      - name: Starting RUNNER
        run: echo "Launching tests for JAVA ${{ matrix.java-version }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run QA Checkstyle
        if: success() || failure()
        run: mvn -B checkstyle:check --file pom.xml